### ISSUE TITLE
Request for Code: Interest of Your Work

### ISSUE THREAD

**Issue by Kaysen-Zhao** [LJC-FVNR/CATS#1]
Dear contributor:
I'm curious about your work. Your paper gives me a lot of thoughts.
Could you share your codes, with that I can understand your work more deeply?
Thanks a lot!
Best Wishes!

**Comment by hbwzj** [comment]
+1。有代码了求分享一波

**Comment by hbwzj** [comment]
Dear esteemed author,
I'm fascinated by your innovative work. Your article has inspired me and I'd like to understand it more deeply. Could you please share your codes with me? It would be greatly appreciated.
Thank you for your contribution!
Best wishes！

**Comment by LJC-FVNR** [comment]
We're glad to hear that our paper has inspired you. You can find a detailed demonstration of how to build CATS with various predictors in our notebook tutorial, `CATS-Tutorial.ipynb`. We are actively working on developing a user interface that encompasses statistical, machine learning, and deep learning methods for time series forecasting. More comprehensive end-to-end practical examples of CATS will be included in our toolkit upon completion. Thank you for your interest!
